# Generated by Django 5.1.5 on 2025-04-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="base/img/default_avatar.png", upload_to="avatars/"
            ),
        ),
    ]
